//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VokabelTrainer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VokabelTrainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berlinale: Movie Festival.
        /// </summary>
        internal static string CelebrationBerlinale {
            get {
                return ResourceManager.GetString("CelebrationBerlinale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Festival in Cannes.
        /// </summary>
        internal static string CelebrationCannes {
            get {
                return ResourceManager.GetString("CelebrationCannes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children and Buddha birthday celebrations in Japan and Korea.
        /// </summary>
        internal static string CelebrationChildrenAndBuddha {
            get {
                return ResourceManager.GetString("CelebrationChildrenAndBuddha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese new year celebrations.
        /// </summary>
        internal static string CelebrationChineseNewYear {
            get {
                return ResourceManager.GetString("CelebrationChineseNewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christians all over the world are celebrating Christmas.
        /// </summary>
        internal static string CelebrationChristmas {
            get {
                return ResourceManager.GetString("CelebrationChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of dancing.
        /// </summary>
        internal static string CelebrationDancingDay {
            get {
                return ResourceManager.GetString("CelebrationDancingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindu light celebration for truth winning over lies.
        /// </summary>
        internal static string CelebrationDiwali {
            get {
                return ResourceManager.GetString("CelebrationDiwali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to African movie festival in Durban.
        /// </summary>
        internal static string CelebrationDurban {
            get {
                return ResourceManager.GetString("CelebrationDurban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christians all over the world are celebrating Easter.
        /// </summary>
        internal static string CelebrationEaster {
            get {
                return ResourceManager.GetString("CelebrationEaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Contest in Europe.
        /// </summary>
        internal static string CelebrationEsc {
            get {
                return ResourceManager.GetString("CelebrationEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslims pilgrim to Mecca: Hajj.
        /// </summary>
        internal static string CelebrationHajj {
            get {
                return ResourceManager.GetString("CelebrationHajj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People all over the world are celebrating new year..
        /// </summary>
        internal static string CelebrationNewYear {
            get {
                return ResourceManager.GetString("CelebrationNewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobel: Prize for Medicine, Chemistry, Physics, Economy, Peace and Literature.
        /// </summary>
        internal static string CelebrationNobelPrize {
            get {
                return ResourceManager.GetString("CelebrationNobelPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olympic summer games.
        /// </summary>
        internal static string CelebrationOlympics {
            get {
                return ResourceManager.GetString("CelebrationOlympics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthodox Christians are celebrating Christmas.
        /// </summary>
        internal static string CelebrationOrthodoxChristmas {
            get {
                return ResourceManager.GetString("CelebrationOrthodoxChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscar: Film Academy awards.
        /// </summary>
        internal static string CelebrationOscar {
            get {
                return ResourceManager.GetString("CelebrationOscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Peace Day.
        /// </summary>
        internal static string CelebrationPeaceDay {
            get {
                return ResourceManager.GetString("CelebrationPeaceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of philosophy.
        /// </summary>
        internal static string CelebrationPhilosophyDay {
            get {
                return ResourceManager.GetString("CelebrationPhilosophyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of psychology.
        /// </summary>
        internal static string CelebrationPsychology {
            get {
                return ResourceManager.GetString("CelebrationPsychology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muslims all over the world are participating in Ramadan.
        /// </summary>
        internal static string CelebrationRamadan {
            get {
                return ResourceManager.GetString("CelebrationRamadan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World reading day.
        /// </summary>
        internal static string CelebrationReadingDay {
            get {
                return ResourceManager.GetString("CelebrationReadingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosh Hashanah: Israeli new year.
        /// </summary>
        internal static string CelebrationRoshHashanah {
            get {
                return ResourceManager.GetString("CelebrationRoshHashanah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Savings Day.
        /// </summary>
        internal static string CelebrationSavingsDay {
            get {
                return ResourceManager.GetString("CelebrationSavingsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Science Day.
        /// </summary>
        internal static string CelebrationScienceDay {
            get {
                return ResourceManager.GetString("CelebrationScienceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halloween.
        /// </summary>
        internal static string CelebrationsHalloween {
            get {
                return ResourceManager.GetString("CelebrationsHalloween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soccer championship.
        /// </summary>
        internal static string CelebrationSoccer {
            get {
                return ResourceManager.GetString("CelebrationSoccer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olympic winter games.
        /// </summary>
        internal static string CelebrationsWinterOlympics {
            get {
                return ResourceManager.GetString("CelebrationsWinterOlympics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timkat: Ethiopian Christians commemorating the Baptism of Jesus.
        /// </summary>
        internal static string CelebrationTimkat {
            get {
                return ResourceManager.GetString("CelebrationTimkat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valentine day.
        /// </summary>
        internal static string CelebrationValentine {
            get {
                return ResourceManager.GetString("CelebrationValentine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loding training results XML file.
        /// </summary>
        internal static string ErrorLoadingTrainingFileHeader {
            get {
                return ResourceManager.GetString("ErrorLoadingTrainingFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while loading training results XML file: {0}.
        /// </summary>
        internal static string ErrorLoadingTrainingFileMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingTrainingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loding vocabulary XML file.
        /// </summary>
        internal static string ErrorLoadingXmlFileHeader {
            get {
                return ResourceManager.GetString("ErrorLoadingXmlFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while loading vocabulary XML file: {0}.
        /// </summary>
        internal static string ErrorLoadingXmlFileMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingXmlFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving training results file: {0}.
        /// </summary>
        internal static string ErrorWhileSavingTrainingFile {
            get {
                return ResourceManager.GetString("ErrorWhileSavingTrainingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving vocabulary file:  {0}.
        /// </summary>
        internal static string ErrorWhileSavingVocabularyFile {
            get {
                return ResourceManager.GetString("ErrorWhileSavingVocabularyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise {0} - {1}.
        /// </summary>
        internal static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following meanings were missing:.
        /// </summary>
        internal static string FollowingMeaningsWereMissing {
            get {
                return ResourceManager.GetString("FollowingMeaningsWereMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following entered meanings were wrong: .
        /// </summary>
        internal static string FollowingMeaningsWereWrong {
            get {
                return ResourceManager.GetString("FollowingMeaningsWereWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following meaning was missing: .
        /// </summary>
        internal static string FollowingMeaningWasMissing {
            get {
                return ResourceManager.GetString("FollowingMeaningWasMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following entered meaning was wrong: .
        /// </summary>
        internal static string FollowingMeaningWasWrong {
            get {
                return ResourceManager.GetString("FollowingMeaningWasWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following meanings were missing:  .
        /// </summary>
        internal static string FollowingMeaningWereMissing {
            get {
                return ResourceManager.GetString("FollowingMeaningWereMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive {0} - {1}.
        /// </summary>
        internal static string Intensive {
            get {
                return ResourceManager.GetString("Intensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite file? .
        /// </summary>
        internal static string LanguageFileAlreadyExistsHeader {
            get {
                return ResourceManager.GetString("LanguageFileAlreadyExistsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language file &quot;{0}&quot; does already exis, do you want to overwrite it?.
        /// </summary>
        internal static string LanguageFileAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("LanguageFileAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.gnu.org/licenses/gpl-2.0.html.
        /// </summary>
        internal static string LocalizedLicenseUrl {
            get {
                return ResourceManager.GetString("LocalizedLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistake!.
        /// </summary>
        internal static string Mistake {
            get {
                return ResourceManager.GetString("Mistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Intensive {0} - {1}.
        /// </summary>
        internal static string MostIntensive {
            get {
                return ResourceManager.GetString("MostIntensive", resourceCulture);
            }
        }
    }
}
