//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VokabelTrainer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VokabelTrainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loding training results XML file ähnelt.
        /// </summary>
        internal static string ErrorLoadingTrainingFileHeader {
            get {
                return ResourceManager.GetString("ErrorLoadingTrainingFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error happened while loading training results XML file: {0} ähnelt.
        /// </summary>
        internal static string ErrorLoadingTrainingFileMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingTrainingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loding vocabulary XML file ähnelt.
        /// </summary>
        internal static string ErrorLoadingXmlFileHeader {
            get {
                return ResourceManager.GetString("ErrorLoadingXmlFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error happened while loading vocabulary XML file: {0} ähnelt.
        /// </summary>
        internal static string ErrorLoadingXmlFileMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingXmlFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while saving training results file: {0} ähnelt.
        /// </summary>
        internal static string ErrorWhileSavingTrainingFile {
            get {
                return ResourceManager.GetString("ErrorWhileSavingTrainingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while saving vocabulary file:  {0} ähnelt.
        /// </summary>
        internal static string ErrorWhileSavingVocabularyFile {
            get {
                return ResourceManager.GetString("ErrorWhileSavingVocabularyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exercise {0} - {1} ähnelt.
        /// </summary>
        internal static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Following meanings were missing: {0} ähnelt.
        /// </summary>
        internal static string FollowingMeaningsWereMissing {
            get {
                return ResourceManager.GetString("FollowingMeaningsWereMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Following entered meanings were wrong:  ähnelt.
        /// </summary>
        internal static string FollowingMeaningsWereWrong {
            get {
                return ResourceManager.GetString("FollowingMeaningsWereWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Following meaning was missing:  ähnelt.
        /// </summary>
        internal static string FollowingMeaningWasMissing {
            get {
                return ResourceManager.GetString("FollowingMeaningWasMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Following entered meaning was wrong:  ähnelt.
        /// </summary>
        internal static string FollowingMeaningWasWrong {
            get {
                return ResourceManager.GetString("FollowingMeaningWasWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Following meanings were missing:   ähnelt.
        /// </summary>
        internal static string FollowingMeaningWereMissing {
            get {
                return ResourceManager.GetString("FollowingMeaningWereMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intensive {0} - {1} ähnelt.
        /// </summary>
        internal static string Intensive {
            get {
                return ResourceManager.GetString("Intensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite file?  ähnelt.
        /// </summary>
        internal static string LanguageFileAlreadyExistsHeader {
            get {
                return ResourceManager.GetString("LanguageFileAlreadyExistsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The language file &quot;{0}&quot; does already exis, do you want to overwrite it? ähnelt.
        /// </summary>
        internal static string LanguageFileAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("LanguageFileAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.gnu.org/licenses/gpl-2.0.html ähnelt.
        /// </summary>
        internal static string LocalizedLicenseUrl {
            get {
                return ResourceManager.GetString("LocalizedLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mistake! ähnelt.
        /// </summary>
        internal static string Mistake {
            get {
                return ResourceManager.GetString("Mistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Most Intensive {0} - {1} ähnelt.
        /// </summary>
        internal static string MostIntensive {
            get {
                return ResourceManager.GetString("MostIntensive", resourceCulture);
            }
        }
    }
}
