name: Build .NET Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increment build number in AssemblyInfo.cs
        shell: pwsh
        run: |
          $file = 'VokabelTrainer/Properties/AssemblyInfo.cs'
          $content = Get-Content $file
          $newContent = @()
          foreach ($line in $content) {
            if ($line -match 'AssemblyVersion\("(\d+)\.(\d+)\.(\d+)\.(\d+)"\)') {
              $major = $matches[1]
              $minor = $matches[2]
              $build = [int]$matches[3] + 1
              $revision = "0"
              $newContent += "[assembly: AssemblyVersion(`"$major.$minor.$build.$revision`")]"
            }
            elseif ($line -match 'AssemblyFileVersion\("(\d+)\.(\d+)\.(\d+)\.(\d+)"\)') {
              $major = $matches[1]
              $minor = $matches[2]
              $build = [int]$matches[3] + 1
              $revision = "0"
              $newContent += "[assembly: AssemblyFileVersion(`"$major.$minor.$build.$revision`")]"
            }
            else {
              $newContent += $line
            }
          }
          Set-Content $file $newContent

      - name: Commit version change
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Automatically incremented build number in AssemblyInfo.cs'
          add: 'VokabelTrainer/Properties/AssemblyInfo.cs'
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore VokabelTrainer.sln

      # - name: Download SNK file from secrets
      #   run: |
      #     $snkBytes = [System.Convert]::FromBase64String("${{ secrets.SNK_FILE }}")
      #     [System.IO.File]::WriteAllBytes("VokabelTrainer/MyKey.snk", $snkBytes)

      # - name: Build and sign with SNK
      #   run: msbuild VokabelTrainer.sln /p:Configuration=Release /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=MyKey.snk


      # - name: Download PFX file from secrets
      #   run: |
      #     $pfxBytes = [System.Convert]::FromBase64String("${{ secrets.PFX_FILE }}")
      #     [System.IO.File]::WriteAllBytes("VokabelTrainer/MyCert.pfx", $pfxBytes)

      # - name: Sign executable with PFX
      #   run: |
      #     & "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe" sign /f VokabelTrainer/MyCert.pfx /p ${{ secrets.PFX_PASSWORD }} /tr http://timestamp.digicert.com /td sha256 /fd sha256 VokabelTrainer/bin/Release/VokabelTrainer.exe

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.8'

      - name: Build solution
        run: msbuild VokabelTrainer.sln /p:Configuration=Release /verbosity:diag



      - name: Upload built zip archive
        uses: actions/upload-artifact@v4
        with:
          name: VokabelTrainer-zip
          path: VokabelTrainer/bin/VokabelTrainer-v1.5.zip

